category: base
doc: | 
  Parameters for controlling external conditions

type: group
NXenvironment(NXobject):
  name:
    doc: | 
      Apparatus identification code/model number; e.g. OC100 011
  short_name:
    doc: | 
      Alternative short name, perhaps for dashboard display like a present Seblock name
  type:
    doc: | 
      Type of apparatus. This could be the SE codes in scheduling database; e.g. OC/100
  description:
    doc: | 
      Description of the apparatus; e.g. 100mm bore orange cryostat with Roots pump
  program:
    doc: | 
      Program controlling the apparatus; e.g. LabView VI name
  position(NXgeometry):
    doc: |       
      The position and orientation of the apparatus.
      Note, it is recommended to use NXtransformations instead.
  depends_on(NX_CHAR):
    doc: |       
      NeXus positions components by applying a set of translations and rotations
      to apply to the component starting from 0, 0, 0. The order of these operations
      is critical and forms what NeXus calls a dependency chain. The depends_on
      field defines the path to the top most operation of the dependency chain or the
      string "." if located in the origin. Usually these operations are stored in a
      NXtransformations group. But NeXus allows them to be stored anywhere.
  (NXtransformations):
    exists: ['min', '0']
    doc: |       
      This is the group recommended for holding the chain of translation
      and rotation operations necessary to position the component within
      the instrument. The dependency chain may however traverse similar groups in
      other component groups.
  (NXnote):
    doc: | 
      Additional information, LabView logs, digital photographs, etc
  (NXsensor):
