category: application
doc: |
  Application definition for a configuration file of the paraprobe-transcoder tool.
  
  This tool is part of the paraprobe-toolbox. Inspect :ref:`NXapm_paraprobe_tool_config` for details.

# symbols:
# doc: |
# The symbols used in the schema to specify e.g. dimensions of arrays.
type: group
NXapm_paraprobe_transcoder_config(NXobject):
  (NXentry):
    exists: ['min', '1', 'max', '1']
    
    # by default for application definitions the value of the exists keyword is required unless it is explicitly specified differently
    definition(NX_CHAR):
      \@version(NX_CHAR):
      enumeration: [NXapm_paraprobe_transcoder_config]
    
    # tool-specific
    transcode(NXapm_paraprobe_tool_config):
      exists: ['min', '1', 'max', '1']
      identifier_analysis(NX_UINT):
        exists: recommended
      reconstruction(NXnote):
        type(NX_CHAR):
        file_name(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        position(NX_CHAR):
        mass_to_charge(NX_CHAR):
      ranging(NXnote):
        doc: |
          Specification of the ranging definition file to use for this analysis.
        type(NX_CHAR):
        file_name(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
    
    # tool-specific parameter
    # filter
    common(NXapm_paraprobe_tool_common):
      status(NX_CHAR):
      (NXprogram):
        exists: ['min', '1', 'max', 'unbounded']
        program(NX_CHAR):
          \@version(NX_CHAR):
      profiling(NXcs_profiling):
        exists: recommended
        start_time(NX_DATE_TIME):
        end_time(NX_DATE_TIME):
        total_elapsed_time(NX_FLOAT):
        current_working_directory(NX_CHAR):

# ++++++++++++++++++++++++++++++++++ SHA HASH ++++++++++++++++++++++++++++++++++
# efe2f4f94318235979207916615347bd6f666273f047adf88a4200b225b6ef7f
# <?xml version="1.0" encoding="UTF-8"?>
# <?xml-stylesheet type="text/xsl" href="nxdlformat.xsl"?>
# <!--
# # NeXus - Neutron and X-ray Common Data Format
# #
# # Copyright (C) 2024-2025 NeXus International Advisory Committee (NIAC)
# #
# # This library is free software; you can redistribute it and/or
# # modify it under the terms of the GNU Lesser General Public
# # License as published by the Free Software Foundation; either
# # version 3 of the License, or (at your option) any later version.
# #
# # This library is distributed in the hope that it will be useful,
# # but WITHOUT ANY WARRANTY; without even the implied warranty of
# # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# # Lesser General Public License for more details.
# #
# # You should have received a copy of the GNU Lesser General Public
# # License along with this library; if not, write to the Free Software
# # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# #
# # For further information, see http://www.nexusformat.org
# -->
# <!--
# symbols:
# doc: |
# The symbols used in the schema to specify e.g. dimensions of arrays.-->
# <definition xmlns="http://definition.nexusformat.org/nxdl/3.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" category="application" type="group" name="NXapm_paraprobe_transcoder_config" extends="NXobject" xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd">
#     <doc>
#         Application definition for a configuration file of the paraprobe-transcoder tool.
#         
#         This tool is part of the paraprobe-toolbox. Inspect :ref:`NXapm_paraprobe_tool_config` for details.
#     </doc>
#     <group type="NXentry" minOccurs="1" maxOccurs="1">
#         <!--by default for application definitions the value of the exists keyword is required unless it is explicitly specified differently-->
#         <field name="definition" type="NX_CHAR">
#             <attribute name="version" type="NX_CHAR"/>
#             <enumeration>
#                 <item value="NXapm_paraprobe_transcoder_config"/>
#             </enumeration>
#         </field>
#         <!--tool-specific-->
#         <group name="transcode" type="NXapm_paraprobe_tool_config" minOccurs="1" maxOccurs="1">
#             <field name="identifier_analysis" type="NX_UINT" recommended="true"/>
#             <group name="reconstruction" type="NXnote">
#                 <field name="type" type="NX_CHAR"/>
#                 <field name="file_name" type="NX_CHAR"/>
#                 <field name="checksum" type="NX_CHAR"/>
#                 <field name="algorithm" type="NX_CHAR"/>
#                 <field name="position" type="NX_CHAR"/>
#                 <field name="mass_to_charge" type="NX_CHAR"/>
#             </group>
#             <group name="ranging" type="NXnote">
#                 <doc>
#                     Specification of the ranging definition file to use for this analysis.
#                 </doc>
#                 <field name="type" type="NX_CHAR"/>
#                 <field name="file_name" type="NX_CHAR"/>
#                 <field name="checksum" type="NX_CHAR"/>
#                 <field name="algorithm" type="NX_CHAR"/>
#             </group>
#         </group>
#         <!--tool-specific parameter
# filter-->
#         <group name="common" type="NXapm_paraprobe_tool_common">
#             <field name="status" type="NX_CHAR"/>
#             <group type="NXprogram" minOccurs="1" maxOccurs="unbounded">
#                 <field name="program" type="NX_CHAR">
#                     <attribute name="version" type="NX_CHAR"/>
#                 </field>
#             </group>
#             <group name="profiling" type="NXcs_profiling" recommended="true">
#                 <field name="start_time" type="NX_DATE_TIME"/>
#                 <field name="end_time" type="NX_DATE_TIME"/>
#                 <field name="total_elapsed_time" type="NX_FLOAT"/>
#                 <field name="current_working_directory" type="NX_CHAR"/>
#             </group>
#         </group>
#     </group>
# </definition>
