category: application
doc: |
  Configuration of a paraprobe-ranger tool run in atom probe microscopy.
symbols:
  doc: The symbols used in the schema to specify e.g. dimensions of arrays.
  n_isotopes: The number of isotopes to consider as building blocks for searching molecular ions.
  n_composition: The number of compositions to consider for molecular ion search tasks.
NXapm_paraprobe_config_ranger:
  (NXentry):
    # by default for appdefs the value of the exists keyword is required
    # unless it is explicitly specified differently
    \@version:
      doc: Version specifier of this application definition.
    definition:
      doc: Official NeXus NXDL schema with which this file was written.
      enumeration: [NXapm_paraprobe_config_ranger]
    program:
      doc: |
        Given name of the program/software/tool with which this NeXus
        (configuration) file was generated.
      \@version:
        doc: |
          Ideally program version plus build number, or commit hash or description
          of ever persistent resources where the source code of the program and
          build instructions can be found so that the program can be configured
          ideally in such a manner that the result of this computational process
          is recreatable in the same deterministic manner.
    time_stamp(NX_DATE_TIME):
      doc: |
        ISO 8601 formatted time code with local time zone offset to UTC
        information included when this configuration file was created.
    analysis_identifier:
      exists: optional
      doc: |
        Ideally, a (globally persistent) unique identifier for referring
        to this analysis.
    analysis_description:
      exists: optional
      doc: Possibility for leaving a free-text description about this analysis.
    results_path:
      exists: optional
      doc: |
        Path to the directory where the tool should store NeXus/HDF5 results
        of this analysis. If not specified results will be stored in the
        current working directory.
    number_of_processes(NX_UINT):
      doc: How many task to perform?
      unit: NX_UNITLESS

    (NXprocess):
      exists: [min, 0, max, infty]
      number_of_ranging_processes(NX_UINT):
        doc: |
          How many range_with_existent_iontypes processes should
          the tool execute as part of the analysis.
        unit: NX_UNITLESS
      number_of_ion_search_processes(NX_UINT):
        doc: |
          How many molecular_ion_search processes should
          the tool execute as part of the analysis.
        unit: NX_UNITLESS

      apply_existent_ranging(NXprocess):
        exists: [min, 0, max, 1]
        dataset(NXapm_input_reconstruction):
          filename:
            \@version:
          dataset_name_reconstruction:
          dataset_name_mass_to_charge:
        iontypes(NXapm_input_ranging):
          filename:
            \@version:
          group_name_iontypes:

        spatial_filter(NXspatial_filter):
          exists: optional
          windowing_method:
            exists: required
          (NXcg_ellipsoid_set):
            exists: optional
            dimensionality(NX_POSINT):
            cardinality(NX_POSINT):
            identifier_offset(NX_INT):
            center(NX_NUMBER):
            half_axes_radii(NX_NUMBER):
            orientation(NX_NUMBER):
          (NXcg_cylinder_set):
            exists: optional
            dimensionality(NX_POSINT):
            cardinality(NX_POSINT):
            identifier_offset(NX_INT):
            center(NX_NUMBER):
            height(NX_NUMBER):
            radii(NX_NUMBER):
          (NXcg_hexahedron_set):
            exists: optional
            dimensionality(NX_POSINT):
            cardinality(NX_POSINT):
            identifier_offset(NX_INT):
            hexahedra(NXcg_face_list_data_structure):
          (NXcs_filter_boolean_mask):
            exists: optional
            number_of_objects(NX_UINT):
            bitdepth(NX_UINT):
            mask(NX_UINT):
            identifier(NX_UINT):
        evaporation_id_filter(NXsubsampling_filter):
          exists: optional
        iontype_filter(NXmatch_filter):
          exists: optional
        hit_multiplicity_filter(NXmatch_filter):
          exists: optional

      molecular_ion_search(NXprocess):
        exists: [min, 0, max, infty]
        assumed_composition_isotopes(NX_UINT):
          doc: |
            A list of pairs of number of protons and either the value 0 (per row)
            or the mass number for all those isotopes which are assumed present
            in a virtual specimen.
            The purpose of this field is to compute also composition-weighted
            products to yield a simple estimation which could potentially help
            scientists to judge if certain molecular ions are to be expected.
            The corresponding setting store_composition_weighted_product should be
            activated.
          unit: NX_UNITLESS
          dimensions:
            rank: 2
            dim: [[1, n_composition], [2, 2]]
        # assumed_composition_value(NX_FLOAT):
        #   doc: |
        #     A list of atomic (at.-%) ! percent values for the composition of each
        #     isotope in the virtual specimen following the sequence of
        #     assumed_composition_isotopes.
        #   unit: NX_DIMENSIONLESS
        #   dimensions:
        #     rank: 1
        #     dim: [[1, n_compositions]]
        isotope_whitelist(NX_UINT):
          doc: |
            A list of pairs of number of protons and mass number for all isotopes
            to consider that can be composed into (molecular) ions, during the
            recursive molecular_ion_search.
          unit: NX_UNITLESS
          dimensions:
            rank: 2
            dim: [[1, n_isotopes], [2, 2]]
        mass_to_charge_interval(NX_FLOAT):
          doc: |
            The mass-to-charge-state ratio interval in which
            all molecular ions are searched.
          unit: NX_ANY
          dimensions:
            rank: 1
            dim: [[1, 2]]
        maximum_charge(NX_UINT):
          doc: The maximum charge that a molecular ion should have.
          unit: NX_UNITLESS
        maximum_number_of_isotopes(NX_UINT):
          doc: |
            The maximum number of isotopes of which the molecular ion
            should be composed. Currently this must not be larger than 32.
            
            Users should be warned that the larger the maximum_charge and
            especially the larger the maximum_number_of_isotopes is chosen,
            the eventually orders of magnitude more costly the search becomes.
            
            This is because paraprobe-ranger computes really all (at least)
            theoretically possible combinations that would have likely a
            mass-to-charge-state ratio in the specified mass_to_charge_interval.
            It is the challenge in atom probe to judge which of these (molecular)
            ions are feasible and also practically possible. This tool does not
            answer this question.
            
            Namely, which specific molecular ion will evaporate, remain stable
            during flight and becomes detected is a complicated and in many cases
            not yet in detail understood phenomenon. The ab-initio conditions
            before and during launch, the local environment, arrangement and field
            as well as the flight phase in an evacuated but not analysis chamber
            with a complex electrical field, eventual laser pulsing in place,
            temperature and remaining atoms or molecules all can have an effect
            which iontypes are really physically evaporating and detected.
          unit: NX_UNITLESS
        store_atomic_mass_sum(NX_BOOLEAN):
          doc: |
            Report the accumulated atomic mass from each isotope building the ion.
            Accounts for each identified ion.
            Relatistic effects are not accounted for.
        store_natural_abundance_product(NX_BOOLEAN):
          doc: |
            Report the product of the natural abundances from each isotope building
            the ion. Accounts for each identified ion.
            
            The value zero indicates it is not possible to build such molecular ion
            from nuclids which are all observationally stable.
            Very small values can give an idea/about how likely such a molecular ion
            is expected to form assuming equal probabilities.
            
            However in atom probe experiments this product has to be modified
            by the (spatially-correlated) local composition in the region from
            which the ions launch because the formation of a molecular ion depends
            as summarized under maximum_number_of_isotopes on the specific
            quantum-mechanical configuration and field state upon launch
            or/and (early state) of flight respectively.
            We are aware that this modified product can have a substantially
            different value than the natural_abundance_product.
            
            Natural abundancies folded with the estimated compositions of the
            specimen can differ by orders of magnitude.
        # add assumed composition of the specimen
        # store_composition_weighted_product(NX_BOOLEAN):
        #   doc: |
        #     Report the product of the composition from each isotope building the
        #     ion. This sets strong constraints on the molecular ions which are
        #     expected to have at all a noteworthy product value.
        #     It should not be forgotten though the computation relies on assumptions:
        #     
        #     * The composition is homogeneous within the virtual specimen.  
        #     * It is a priori know which nuclids the specimen is build of.  
        #     
        store_charge_state(NX_BOOLEAN):
          doc: |
            Report the charge state of the ions.
        store_disjoint_isotopes(NX_BOOLEAN):
          doc: |
            Report if identified ions should be characterized
            wrt to their number of disjoint isotopes.

      check_existent_ranging(NXprocess):
        exists: [min, 0, max, 1]
        iontypes(NXapm_input_ranging):
          filename:
            \@version:
          group_name_iontypes:

    performance(NXcs_profiling):
      current_working_directory: