category: application
doc: |
  Application definition for a configuration file of the paraprobe-tessellator tool.
  
  The tool paraprobe-tessellator computes a tessellation of the reconstructed positions.

# n_control_points: The number of control points for tessellating regions instead of tessellating the volume about ion positions.
# an example for limited conditions in NeXus
# if windowing_method is entire_dataset: no constraint on existence of NXcg and NXcs instances
# if windowing_method is union_of_primitives: sum of cardinality of NXcg >= 0
# if windowing_method is bitmasked_points: sum cardinality of NXcg := 0 and cardinality of NXcs_filter_boolean_mask == 1
type: group
NXapm_paraprobe_tessellator_config(NXapm_paraprobe_tool_config):
  (NXentry):
    exists: ['min', '1', 'max', '1']
    definition(NX_CHAR):
      enumeration: [NXapm_paraprobe_tessellator_config]
    tessellateID(NXapm_paraprobe_tool_parameters):
      nameType: partial
      exists: ['min', '1', 'max', '1']
      surface_distance(NXnote):
        exists: optional
        file_name(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        distance(NX_CHAR):
      method(NX_CHAR):
        doc: |
          The method used to compute the tessellation.
          The value *default* configures the computation of the Voronoi tessellation.
        
        # check versions prior paraprobe-toolbox v0.5 for control_point-based method
        enumeration: [default]
      has_cell_volume(NX_BOOLEAN):
        doc: |
          Specifies if the tool should report the volume of each cell.
      has_cell_neighbors(NX_BOOLEAN):
        doc: |
          Specifies if the tool should report the first-order neighbors of each cell.
      has_cell_geometry(NX_BOOLEAN):
        doc: |
          Specifies if the tool should report the facets and vertices of each cell.
      has_cell_edge_detection(NX_BOOLEAN):
        doc: |
          Specifies if the tool should report for each cell if it makes contact with
          the tight axis-aligned bounding box about the point cloud.
          This can be used to identify if the shape of the cell is likely affected
          by the edge of the dataset or if cells are deeply enough embedded
          into the point cloud so that the shape of their cells are not affected
          anymore by the boundary. This is valuable information to judge
          about the significance of finite size effects.
  
  # erosion_distance(NX_FLOAT):
  # doc: |
  # Maximum distance for which cells are eroded.
  # unit: NX_LENGTH
  # \@units: nm
  # minValue: EPSILON

# ++++++++++++++++++++++++++++++++++ SHA HASH ++++++++++++++++++++++++++++++++++
# e6e3a7f778a18d7f63551925def7709ee25b82f76f8a29337749964fc0f6199a
# <?xml version="1.0" encoding="UTF-8"?>
# <?xml-stylesheet type="text/xsl" href="nxdlformat.xsl"?>
# <!--
# # NeXus - Neutron and X-ray Common Data Format
# #
# # Copyright (C) 2024-2025 NeXus International Advisory Committee (NIAC)
# #
# # This library is free software; you can redistribute it and/or
# # modify it under the terms of the GNU Lesser General Public
# # License as published by the Free Software Foundation; either
# # version 3 of the License, or (at your option) any later version.
# #
# # This library is distributed in the hope that it will be useful,
# # but WITHOUT ANY WARRANTY; without even the implied warranty of
# # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# # Lesser General Public License for more details.
# #
# # You should have received a copy of the GNU Lesser General Public
# # License along with this library; if not, write to the Free Software
# # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# #
# # For further information, see http://www.nexusformat.org
# -->
# <!--
# n_control_points: The number of control points for tessellating regions instead of tessellating the volume about ion positions.
# an example for limited conditions in NeXus
# if windowing_method is entire_dataset: no constraint on existence of NXcg and NXcs instances
# if windowing_method is union_of_primitives: sum of cardinality of NXcg >= 0
# if windowing_method is bitmasked_points: sum cardinality of NXcg := 0 and cardinality of NXcs_filter_boolean_mask == 1-->
# <definition xmlns="http://definition.nexusformat.org/nxdl/3.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" category="application" type="group" name="NXapm_paraprobe_tessellator_config" extends="NXapm_paraprobe_tool_config" xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd">
#     <doc>
#         Application definition for a configuration file of the paraprobe-tessellator tool.
#         
#         The tool paraprobe-tessellator computes a tessellation of the reconstructed positions.
#     </doc>
#     <group type="NXentry" minOccurs="1" maxOccurs="1">
#         <field name="definition" type="NX_CHAR">
#             <enumeration>
#                 <item value="NXapm_paraprobe_tessellator_config"/>
#             </enumeration>
#         </field>
#         <group name="tessellateID" type="NXapm_paraprobe_tool_parameters" nameType="partial" minOccurs="1" maxOccurs="1">
#             <group name="surface_distance" type="NXnote" optional="true">
#                 <field name="file_name" type="NX_CHAR"/>
#                 <field name="checksum" type="NX_CHAR"/>
#                 <field name="algorithm" type="NX_CHAR"/>
#                 <field name="distance" type="NX_CHAR"/>
#             </group>
#             <field name="method" type="NX_CHAR">
#                 <doc>
#                     The method used to compute the tessellation.
#                     The value *default* configures the computation of the Voronoi tessellation.
#                 </doc>
#                 <!--check versions prior paraprobe-toolbox v0.5 for control_point-based method-->
#                 <enumeration>
#                     <item value="default"/>
#                 </enumeration>
#             </field>
#             <field name="has_cell_volume" type="NX_BOOLEAN">
#                 <doc>
#                     Specifies if the tool should report the volume of each cell.
#                 </doc>
#             </field>
#             <field name="has_cell_neighbors" type="NX_BOOLEAN">
#                 <doc>
#                     Specifies if the tool should report the first-order neighbors of each cell.
#                 </doc>
#             </field>
#             <field name="has_cell_geometry" type="NX_BOOLEAN">
#                 <doc>
#                     Specifies if the tool should report the facets and vertices of each cell.
#                 </doc>
#             </field>
#             <field name="has_cell_edge_detection" type="NX_BOOLEAN">
#                 <doc>
#                     Specifies if the tool should report for each cell if it makes contact with
#                     the tight axis-aligned bounding box about the point cloud.
#                     This can be used to identify if the shape of the cell is likely affected
#                     by the edge of the dataset or if cells are deeply enough embedded
#                     into the point cloud so that the shape of their cells are not affected
#                     anymore by the boundary. This is valuable information to judge
#                     about the significance of finite size effects.
#                 </doc>
#             </field>
#         </group>
#     </group>
#     <!--erosion_distance(NX_FLOAT):
# doc: |
# Maximum distance for which cells are eroded.
# unit: NX_LENGTH
# \@units: nm
# minValue: EPSILON-->
# </definition>
