category: application
doc: |
  Application definition for a (configuration) file of a tool from the paraprobe-toolbox.
  
  The paraprobe-toolbox is a collection of open-source tools for performing
  efficient analyses of point cloud data where each point can represent atoms or
  (molecular) ions. A key application of the toolbox has been for research in the
  field of Atom Probe Tomography (APT) and related Field Ion Microscopy (FIM):
  
  * `paraprobe-toolbox <https://www.gitlab.com/paraprobe/paraprobe-toolbox>`_
  * `M. Kühbach et al. <https://paraprobe-toolbox.readthedocs.io/en/main/>`_
  
  The toolbox does not replace but complements existent software tools in this
  research field. Given its capabilities of handling points as objects with
  properties and enabling analyses of the spatial arrangement of and inter-
  sections between geometric primitives, the software can equally be used
  for analyzing data in Materials Science and Materials Engineering.
type: group
NXapm_paraprobe_tool_config(NXobject):
  (NXentry):
    exists: ['min', '1', 'max', '1']
    definition(NX_CHAR):
      \@version(NX_CHAR):
    TASKCONFIG(NXapm_paraprobe_tool_parameters):
      nameType: any
      exists: ['min', '1', 'max', 'unbounded']
      doc: |
        A specific configuration to achieve a processing result
      identifier_analysis(NX_UINT):
        exists: recommended
      reconstruction(NXnote):
        file_name(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        position(NX_CHAR):
        mass_to_charge(NX_CHAR):
      ranging(NXnote):
        file_name(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        ranging_definitions(NX_CHAR):
      spatial_filter(NXspatial_filter):
        windowing_method(NX_CHAR):
        hexahedron_set(NXcg_hexahedron):
          exists: optional
          dimensionality(NX_POSINT):
          cardinality(NX_POSINT):
          index_offset(NX_INT):
          hexahedra(NXcg_face_list_data_structure):
            vertices(NX_UINT):
        cylinder_set(NXcg_cylinder):
          exists: optional
          dimensionality(NX_POSINT):
          cardinality(NX_POSINT):
          index_offset(NX_INT):
          center(NX_NUMBER):
          height(NX_NUMBER):
          radii(NX_NUMBER):
        ellipsoid_set(NXcg_ellipsoid):
          exists: optional
          dimensionality(NX_POSINT):
          cardinality(NX_POSINT):
          index_offset(NX_INT):
          center(NX_NUMBER):
          half_axes_radii(NX_NUMBER):
          orientation(NX_NUMBER):
        polyhedron_set(NXcg_polyhedron):
          exists: optional
        bitmask(NXcs_filter_boolean_mask):
          exists: optional
          number_of_objects(NX_UINT):
          bitdepth(NX_UINT):
          mask(NX_UINT):
      evaporation_id_filter(NXsubsampling_filter):
        exists: optional
        min(NX_INT):
        increment(NX_INT):
        max(NX_INT):
      iontype_filter(NXmatch_filter):
        exists: optional
        method(NX_CHAR):
        match(NX_NUMBER):
      hit_multiplicity_filter(NXmatch_filter):
        exists: optional
        method(NX_CHAR):
        match(NX_NUMBER):
    common(NXapm_paraprobe_tool_common):
      status(NX_CHAR):
      programID(NXprogram):
        nameType: partial
        exists: ['min', '1', 'max', 'unbounded']
        program(NX_CHAR):
          \@version(NX_CHAR):
      profiling(NXcs_profiling):
        exists: recommended
        start_time(NX_DATE_TIME):
        end_time(NX_DATE_TIME):
        total_elapsed_time(NX_FLOAT):

# ++++++++++++++++++++++++++++++++++ SHA HASH ++++++++++++++++++++++++++++++++++
# 6c285e190e068a891ed7cf82c89d7eaba019c7ba2516600bd8fbc0d8f0e8d4e0
# <?xml version="1.0" encoding="UTF-8"?>
# <?xml-stylesheet type="text/xsl" href="nxdlformat.xsl"?>
# <!--
# # NeXus - Neutron and X-ray Common Data Format
# #
# # Copyright (C) 2025-2025 NeXus International Advisory Committee (NIAC)
# #
# # This library is free software; you can redistribute it and/or
# # modify it under the terms of the GNU Lesser General Public
# # License as published by the Free Software Foundation; either
# # version 3 of the License, or (at your option) any later version.
# #
# # This library is distributed in the hope that it will be useful,
# # but WITHOUT ANY WARRANTY; without even the implied warranty of
# # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# # Lesser General Public License for more details.
# #
# # You should have received a copy of the GNU Lesser General Public
# # License along with this library; if not, write to the Free Software
# # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# #
# # For further information, see http://www.nexusformat.org
# -->
# <definition xmlns="http://definition.nexusformat.org/nxdl/3.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" category="application" type="group" name="NXapm_paraprobe_tool_config" extends="NXobject" xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd">
#     <doc>
#         Application definition for a (configuration) file of a tool from the paraprobe-toolbox.
#         
#         The paraprobe-toolbox is a collection of open-source tools for performing
#         efficient analyses of point cloud data where each point can represent atoms or
#         (molecular) ions. A key application of the toolbox has been for research in the
#         field of Atom Probe Tomography (APT) and related Field Ion Microscopy (FIM):
#         
#         * `paraprobe-toolbox &lt;https://www.gitlab.com/paraprobe/paraprobe-toolbox&gt;`_
#         * `M. Kühbach et al. &lt;https://paraprobe-toolbox.readthedocs.io/en/main/&gt;`_
#         
#         The toolbox does not replace but complements existent software tools in this
#         research field. Given its capabilities of handling points as objects with
#         properties and enabling analyses of the spatial arrangement of and inter-
#         sections between geometric primitives, the software can equally be used
#         for analyzing data in Materials Science and Materials Engineering.
#     </doc>
#     <group type="NXentry" minOccurs="1" maxOccurs="1">
#         <field name="definition" type="NX_CHAR">
#             <attribute name="version" type="NX_CHAR"/>
#         </field>
#         <group name="TASKCONFIG" type="NXapm_paraprobe_tool_parameters" nameType="any" minOccurs="1" maxOccurs="unbounded">
#             <doc>
#                 A specific configuration to achieve a processing result
#             </doc>
#             <field name="identifier_analysis" type="NX_UINT" recommended="true"/>
#             <group name="reconstruction" type="NXnote">
#                 <field name="file_name" type="NX_CHAR"/>
#                 <field name="checksum" type="NX_CHAR"/>
#                 <field name="algorithm" type="NX_CHAR"/>
#                 <field name="position" type="NX_CHAR"/>
#                 <field name="mass_to_charge" type="NX_CHAR"/>
#             </group>
#             <group name="ranging" type="NXnote">
#                 <field name="file_name" type="NX_CHAR"/>
#                 <field name="checksum" type="NX_CHAR"/>
#                 <field name="algorithm" type="NX_CHAR"/>
#                 <field name="ranging_definitions" type="NX_CHAR"/>
#             </group>
#             <group name="spatial_filter" type="NXspatial_filter">
#                 <field name="windowing_method" type="NX_CHAR"/>
#                 <group name="hexahedron_set" type="NXcg_hexahedron" optional="true">
#                     <field name="dimensionality" type="NX_POSINT"/>
#                     <field name="cardinality" type="NX_POSINT"/>
#                     <field name="index_offset" type="NX_INT"/>
#                     <group name="hexahedra" type="NXcg_face_list_data_structure">
#                         <field name="vertices" type="NX_UINT"/>
#                     </group>
#                 </group>
#                 <group name="cylinder_set" type="NXcg_cylinder" optional="true">
#                     <field name="dimensionality" type="NX_POSINT"/>
#                     <field name="cardinality" type="NX_POSINT"/>
#                     <field name="index_offset" type="NX_INT"/>
#                     <field name="center" type="NX_NUMBER"/>
#                     <field name="height" type="NX_NUMBER"/>
#                     <field name="radii" type="NX_NUMBER"/>
#                 </group>
#                 <group name="ellipsoid_set" type="NXcg_ellipsoid" optional="true">
#                     <field name="dimensionality" type="NX_POSINT"/>
#                     <field name="cardinality" type="NX_POSINT"/>
#                     <field name="index_offset" type="NX_INT"/>
#                     <field name="center" type="NX_NUMBER"/>
#                     <field name="half_axes_radii" type="NX_NUMBER"/>
#                     <field name="orientation" type="NX_NUMBER"/>
#                 </group>
#                 <group name="polyhedron_set" type="NXcg_polyhedron" optional="true"/>
#                 <group name="bitmask" type="NXcs_filter_boolean_mask" optional="true">
#                     <field name="number_of_objects" type="NX_UINT"/>
#                     <field name="bitdepth" type="NX_UINT"/>
#                     <field name="mask" type="NX_UINT"/>
#                 </group>
#             </group>
#             <group name="evaporation_id_filter" type="NXsubsampling_filter" optional="true">
#                 <field name="min" type="NX_INT"/>
#                 <field name="increment" type="NX_INT"/>
#                 <field name="max" type="NX_INT"/>
#             </group>
#             <group name="iontype_filter" type="NXmatch_filter" optional="true">
#                 <field name="method" type="NX_CHAR"/>
#                 <field name="match" type="NX_NUMBER"/>
#             </group>
#             <group name="hit_multiplicity_filter" type="NXmatch_filter" optional="true">
#                 <field name="method" type="NX_CHAR"/>
#                 <field name="match" type="NX_NUMBER"/>
#             </group>
#         </group>
#         <group name="common" type="NXapm_paraprobe_tool_common">
#             <field name="status" type="NX_CHAR"/>
#             <group name="programID" type="NXprogram" nameType="partial" minOccurs="1" maxOccurs="unbounded">
#                 <field name="program" type="NX_CHAR">
#                     <attribute name="version" type="NX_CHAR"/>
#                 </field>
#             </group>
#             <group name="profiling" type="NXcs_profiling" recommended="true">
#                 <field name="start_time" type="NX_DATE_TIME"/>
#                 <field name="end_time" type="NX_DATE_TIME"/>
#                 <field name="total_elapsed_time" type="NX_FLOAT"/>
#             </group>
#         </group>
#     </group>
# </definition>
