name: GH pages fairmat proposal

on:
  push:
    branches: [fairmat]
  pull_request:
    branches: [fairmat]

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7
    - name: test
      run: make test
    - name: prepare
      run: make prepare
    - name: html
      run: make html
    - name: Deploy
      if: steps.branch-name.outputs.is_default == 'true'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: build/manual/build/html
        branch: fairmat-docs
        target-folder: docs
        clean: false
    - name: Deploy PR
      if: steps.branch-name.outputs.is_default == 'false'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: build/manual/build/html
        branch: fairmat-docs
        target-folder: docs/${{ steps.branch-name.outputs.current_branch }}
        clean: false